/**
 * assemble.js — FFmpeg command builder & executor
 *
 * Two-pass approach:
 *   Pass 1 — Process each scene into an intermediate file (trim, scale, pad)
 *   Pass 2 — Concatenate intermediates, mix audio, burn subtitles → final MP4
 *
 * Uses fluent-ffmpeg (never raw exec).
 */

const fs = require("fs");
const path = require("path");
const ffmpeg = require("fluent-ffmpeg");

/**
 * Process a single scene: trim to duration, scale to 1080×1920, pad with black.
 *
 * @param {string} inputPath      — path to source video
 * @param {string} outputPath     — path for processed intermediate
 * @param {number} durationSeconds — how many seconds to keep
 * @returns {Promise<string>} outputPath
 */
function processScene(inputPath, outputPath, durationSeconds) {
  return new Promise((resolve, reject) => {
    let lastStderr = "";

    ffmpeg(inputPath)
      .duration(durationSeconds)
      .videoFilters([
        // Scale to fit within 1080×1920 while keeping aspect ratio
        "scale=1080:1920:force_original_aspect_ratio=decrease",
        // Pad to exactly 1080×1920, centred, black bars
        "pad=1080:1920:(ow-iw)/2:(oh-ih)/2:black",
        // Normalise sample aspect ratio
        "setsar=1",
      ])
      .outputOptions([
        "-c:v", "libx264",
        "-preset", "fast",
        "-crf", "23",
        "-an",                 // strip audio — we mix it later
        "-y",                  // overwrite without asking
      ])
      .on("stderr", (line) => {
        lastStderr = line;
        console.log(`[ffmpeg·scene] ${line}`);
      })
      .on("end", () => resolve(outputPath))
      .on("error", (err) => {
        reject(new Error(`Scene processing failed: ${lastStderr || err.message}`));
      })
      .save(outputPath);
  });
}

/**
 * Write a concat demuxer file listing all intermediate videos.
 *
 * @param {string[]} filePaths — ordered list of intermediate MP4 paths
 * @param {string}  listPath  — where to write the list file
 * @returns {string} listPath
 */
function writeConcatList(filePaths, listPath) {
  const lines = filePaths.map((fp) => `file '${fp.replace(/'/g, "'\\''")}'`);
  fs.writeFileSync(listPath, lines.join("\n"), "utf-8");
  return listPath;
}

/**
 * Build and run the full assembly pipeline.
 *
 * @param {Array<{ video_path: string, duration_seconds: number, caption: string }>} scenes
 * @param {string} audioPath     — downloaded audio file
 * @param {string} outputPath    — final MP4 destination
 * @param {number} totalSeconds  — desired total length
 * @returns {Promise<string>} outputPath on success
 */
async function buildAndRun(scenes, audioPath, outputPath, totalSeconds) {
  const jobDir = path.dirname(outputPath);

  // ── Pass 1: process each scene ────────────────────────────
  const intermediates = [];

  for (let i = 0; i < scenes.length; i++) {
    const scene = scenes[i];
    const intermediatePath = path.join(jobDir, `scene_${i}.mp4`);
    console.log(`[assemble] Processing scene ${i + 1}/${scenes.length}…`);
    await processScene(scene.video_path, intermediatePath, scene.duration_seconds);
    intermediates.push(intermediatePath);
  }

  // ── Concat list file ──────────────────────────────────────
  const concatListPath = path.join(jobDir, "concat_list.txt");
  writeConcatList(intermediates, concatListPath);

  // ── SRT path (must already exist, generated by render.js) ─
  const srtPath = path.join(jobDir, "subtitles.srt");

  // ── Pass 2: concat + audio + subtitles → final MP4 ───────
  return new Promise((resolve, reject) => {
    let lastStderr = "";

    // Escape the SRT path for the subtitles filter.
    // On Linux (Docker), paths are already forward-slash based.
    // Only special chars that need escaping in the filtergraph are: \ : '
    const escapedSrt = srtPath
      .replace(/\\/g, "/")          // Windows backslash → forward slash (no-op on Linux)
      .replace(/'/g, "\\'")         // escape single quotes
      .replace(/\[/g, "\\[")        // escape square brackets
      .replace(/\]/g, "\\]");       // escape square brackets
    // Note: do NOT escape colons on Linux — /tmp/... paths have no colons

    // Subtitle style: bold white text with black background box
    // IMPORTANT:
    //   - Do NOT include FontName with spaces (breaks FFmpeg filtergraph parsing)
    //     libass will use the only installed font (DejaVu Sans) automatically
    //   - Join with \, (escaped comma) NOT , — commas are filter-chain separators in FFmpeg
    const subtitleStyle = [
      "FontSize=18",
      "Bold=1",
      "PrimaryColour=&H00FFFFFF",     // white text (ABGR hex)
      "OutlineColour=&H00000000",     // black outline
      "BackColour=&H80000000",        // semi-transparent black background
      "BorderStyle=3",                // box-style background
      "Outline=2",
      "Shadow=1",
      "Alignment=2",                  // bottom-centre (ASS alignment)
      "MarginV=60",                   // 60px from bottom
      "MarginL=40",
      "MarginR=40",
    ].join("\\,");                    // \, not , — avoids FFmpeg filtergraph splitting

    const filterStr = `subtitles='${escapedSrt}':force_style='${subtitleStyle}'`;
    console.log(`[assemble] Subtitle filter: ${filterStr}`);

    const cmd = ffmpeg()
      // Video input: concat demuxer
      .input(concatListPath)
      .inputOptions(["-f", "concat", "-safe", "0"])
      // Audio input
      .input(audioPath)
      .outputOptions([
        // Video codec
        "-c:v", "libx264",
        "-preset", "fast",
        "-crf", "23",
        // Audio codec
        "-c:a", "aac",
        "-b:a", "128k",
        // Take video from input 0, audio from input 1
        "-map", "0:v:0",
        "-map", "1:a:0",
        // Trim the final output to totalSeconds
        "-t", String(totalSeconds),
        // Burn subtitles with styling
        "-vf", filterStr,
        // Shortest — stop when shortest stream ends
        "-shortest",
        // Overwrite
        "-y",
      ]);


    cmd
      .on("stderr", (line) => {
        lastStderr = line;
        console.log(`[ffmpeg·final] ${line}`);
      })
      .on("end", () => resolve(outputPath))
      .on("error", (err) => {
        reject(new Error(`Final assembly failed: ${lastStderr || err.message}`));
      })
      .save(outputPath);
  });
}

module.exports = { buildAndRun };
