/**
 * assemble.js — FFmpeg command builder & executor
 *
 * Two-pass approach:
 *   Pass 1 — Process each scene into an intermediate file (trim, scale, pad)
 *   Pass 2 — Concatenate intermediates, mix audio, burn subtitles → final MP4
 *
 * Uses fluent-ffmpeg (never raw exec).
 */

const fs = require("fs");
const path = require("path");
const ffmpeg = require("fluent-ffmpeg");

/**
 * Process a single scene: trim to duration, scale to 1080×1920, pad with black.
 *
 * @param {string} inputPath      — path to source video
 * @param {string} outputPath     — path for processed intermediate
 * @param {number} durationSeconds — how many seconds to keep
 * @returns {Promise<string>} outputPath
 */
function processScene(inputPath, outputPath, durationSeconds) {
  return new Promise((resolve, reject) => {
    let lastStderr = "";

    ffmpeg(inputPath)
      .duration(durationSeconds)
      .complexFilter([
        // 1. Create blurred background: scale to fill (increase), crop center, strong boxblur
        "[0:v]scale=1080:1920:force_original_aspect_ratio=increase,crop=1080:1920,boxblur=20:20[bg]",
        // 2. Create foreground: scale to fit (decrease)
        "[0:v]scale=1080:1920:force_original_aspect_ratio=decrease[fg]",
        // 3. Overlay foreground on background, centered
        "[bg][fg]overlay=(main_w-overlay_w)/2:(main_h-overlay_h)/2,setsar=1"
      ])
      .outputOptions([
        "-c:v", "libx264",
        "-preset", "fast",
        "-crf", "23",
        "-an",                 // strip audio — we mix it later
        "-y",                  // overwrite without asking
      ])
      .on("stderr", (line) => {
        lastStderr = line;
        // console.log(`[ffmpeg·scene] ${line}`); // Removed to reduce spam
      })
      .on("end", () => resolve(outputPath))
      .on("error", (err) => {
        reject(new Error(`Scene processing failed: ${lastStderr || err.message}`));
      })
      .save(outputPath);
  });
}

/**
 * Write a concat demuxer file listing all intermediate videos.
 *
 * @param {string[]} filePaths — ordered list of intermediate MP4 paths
 * @param {string}  listPath  — where to write the list file
 * @returns {string} listPath
 */
function writeConcatList(filePaths, listPath) {
  const lines = filePaths.map((fp) => `file '${fp.replace(/'/g, "'\\''")}'`);
  fs.writeFileSync(listPath, lines.join("\n"), "utf-8");
  return listPath;
}

/**
 * Build and run the full assembly pipeline.
 *
 * @param {Array<{ video_path: string, duration_seconds: number, caption: string }>} scenes
 * @param {string} audioPath     — downloaded audio file
 * @param {string} outputPath    — final MP4 destination
 * @param {number} totalSeconds  — desired total length
 * @returns {Promise<string>} outputPath on success
 */
async function buildAndRun(scenes, audioPath, outputPath, totalSeconds) {
  const jobDir = path.dirname(outputPath);

  // ── Pass 1: process each scene ────────────────────────────
  const intermediates = [];

  for (let i = 0; i < scenes.length; i++) {
    const scene = scenes[i];
    const intermediatePath = path.join(jobDir, `scene_${i}.mp4`);
    console.log(`[assemble] Processing scene ${i + 1}/${scenes.length}…`);
    await processScene(scene.video_path, intermediatePath, scene.duration_seconds);
    intermediates.push(intermediatePath);
  }

  // ── Concat list file ──────────────────────────────────────
  const concatListPath = path.join(jobDir, "concat_list.txt");
  writeConcatList(intermediates, concatListPath);

  // ── Pass 2: concat + audio + subtitles → final MP4 ───────
  return new Promise((resolve, reject) => {
    let lastStderr = "";

    // ASS subtitle file path (generated by render.js using subtitle.js)
    const assPath = path.join(jobDir, "subtitles.ass");

    // Escape the ASS path for FFmpeg filtergraph.
    // On Linux (Docker), just need to handle single quotes.
    const escapedAss = assPath
      .replace(/\\/g, "/")          // Windows backslash → forward (no-op on Linux)
      .replace(/'/g, "\\'")         // escape single quotes
      .replace(/\[/g, "\\[")
      .replace(/\]/g, "\\]");

    // ASS filter — all styling is embedded in the .ass file, no force_style needed
    const filterStr = `ass='${escapedAss}'`;

    const cmd = ffmpeg()
      // Video input: concat demuxer
      .input(concatListPath)
      .inputOptions(["-f", "concat", "-safe", "0"])
      // Audio input
      .input(audioPath)
      .outputOptions([
        // Video codec
        "-c:v", "libx264",
        "-preset", "fast",
        "-crf", "23",
        // Audio codec
        "-c:a", "aac",
        "-b:a", "128k",
        // Take video from input 0, audio from input 1
        "-map", "0:v:0",
        "-map", "1:a:0",
        // Trim the final output to totalSeconds
        "-t", String(totalSeconds),
        // Burn subtitles (ASS format — style embedded in file)
        "-vf", filterStr,
        // Shortest — stop when shortest stream ends
        "-shortest",
        // Overwrite
        "-y",
      ]);



    cmd
      .on("stderr", (line) => {
        lastStderr = line;
        // console.log(`[ffmpeg·final] ${line}`); // Removed to reduce spam
      })
      .on("end", () => resolve(outputPath))
      .on("error", (err) => {
        reject(new Error(`Final assembly failed: ${lastStderr || err.message}`));
      })
      .save(outputPath);
  });
}

module.exports = { buildAndRun };
