/**
 * assemble.js — FFmpeg command builder & executor
 *
 * Two-pass approach:
 *   Pass 1 — Process each scene into an intermediate file (trim, scale, pad)
 *   Pass 2 — Concatenate intermediates, mix audio, burn subtitles → final MP4
 *
 * Uses fluent-ffmpeg (never raw exec).
 */

const fs = require("fs");
const path = require("path");
const ffmpeg = require("fluent-ffmpeg");
const { execSync } = require('child_process');

/**
 * Process a single scene: trim to duration, scale to 1080×1920, pad with black.
 *
 * @param {string} inputPath      — path to source video
 * @param {string} outputPath     — path for processed intermediate
 * @param {number} durationSeconds — how many seconds to keep
 * @returns {Promise<string>} outputPath
 */
function processScene(inputPath, outputPath, durationSeconds) {
  return new Promise((resolve, reject) => {
    let lastStderr = "";

    ffmpeg(inputPath)
      .duration(durationSeconds)
      .complexFilter([
        // 1. Create blurred background: scale to fill (increase), crop center, strong boxblur
        "[0:v]scale=1080:1920:force_original_aspect_ratio=increase,crop=1080:1920,boxblur=20:20[bg]",
        // 2. Create foreground: scale to fit (decrease)
        "[0:v]scale=1080:1920:force_original_aspect_ratio=decrease[fg]",
        // 3. Overlay foreground on background, centered
        "[bg][fg]overlay=(main_w-overlay_w)/2:(main_h-overlay_h)/2,setsar=1"
      ])
      .outputOptions([
        "-c:v", "libx264",
        "-preset", "fast",
        "-crf", "23",
        "-an",                 // strip audio — we mix it later
        "-y",                  // overwrite without asking
      ])
      .on("stderr", (line) => {
        lastStderr = line;
        // console.log(`[ffmpeg·scene] ${line}`); // Removed to reduce spam
      })
      .on("end", () => resolve(outputPath))
      .on("error", (err) => {
        reject(new Error(`Scene processing failed: ${lastStderr || err.message}`));
      })
      .save(outputPath);
  });
}

/**
 * Write a concat demuxer file listing all intermediate videos.
 *
 * @param {string[]} filePaths — ordered list of intermediate MP4 paths
 * @param {string}  listPath  — where to write the list file
 * @returns {string} listPath
 */
function writeConcatList(filePaths, listPath) {
  const lines = filePaths.map((fp) => `file '${fp.replace(/'/g, "'\\''")}'`);
  fs.writeFileSync(listPath, lines.join("\n"), "utf-8");
  return listPath;
}

/**
 * Build and run the full assembly pipeline.
 *
 * @param {Array<{ video_path: string, duration_seconds: number, caption: string }>} scenes
 * @param {string} audioPath     — downloaded audio file
 * @param {string} outputPath    — final MP4 destination
 * @param {number} totalSeconds  — desired total length
 * @returns {Promise<string>} outputPath on success
 */
async function buildAndRun(scenes, audioPath, outputPath, totalSeconds) {
  const jobDir = path.dirname(outputPath);

  // ── Pass 1: process each scene ────────────────────────────
  const intermediates = [];

  for (let i = 0; i < scenes.length; i++) {
    const scene = scenes[i];
    const intermediatePath = path.join(jobDir, `scene_${i}.mp4`);
    console.log(`[assemble] Processing scene ${i + 1}/${scenes.length}…`);
    await processScene(scene.video_path, intermediatePath, scene.duration_seconds);
    intermediates.push(intermediatePath);
  }

  // ── Concat list file ──────────────────────────────────────
  const concatListPath = path.join(jobDir, "concat_list.txt");
  writeConcatList(intermediates, concatListPath);

  // ── Pass 2: concat + audio + subtitles → final MP4 ───────
  return new Promise((resolve, reject) => {
    let lastStderr = "";

    // ASS subtitle file path (generated by render.js using subtitle.js)
    const assPath = path.join(jobDir, "subtitles.ass");

    // Escape the ASS path for FFmpeg filtergraph.
    // On Linux (Docker), just need to handle single quotes.
    const escapedAss = assPath
      .replace(/\\/g, "/")          // Windows backslash → forward (no-op on Linux)
      .replace(/'/g, "\\'")         // escape single quotes
      .replace(/\[/g, "\\[")
      .replace(/\]/g, "\\]");

    // ASS filter — all styling is embedded in the .ass file, no force_style needed
    const filterStr = `ass='${escapedAss}'`;

    const cmd = ffmpeg()
      // Video input: concat demuxer
      .input(concatListPath)
      .inputOptions(["-f", "concat", "-safe", "0"])
      // Audio input
      .input(audioPath)
      .outputOptions([
        // Video codec
        "-c:v", "libx264",
        "-preset", "fast",
        "-crf", "23",
        // Audio codec
        "-c:a", "aac",
        "-b:a", "128k",
        // Take video from input 0, audio from input 1
        "-map", "0:v:0",
        "-map", "1:a:0",
        // Trim the final output to totalSeconds
        "-t", String(totalSeconds),
        // Burn subtitles (ASS format — style embedded in file)
        "-vf", filterStr,
        // Shortest — stop when shortest stream ends
        "-shortest",
        // Overwrite
        "-y",
      ]);



    cmd
      .on("stderr", (line) => {
        lastStderr = line;
        // console.log(`[ffmpeg·final] ${line}`); // Removed to reduce spam
      })
      .on("end", () => resolve(outputPath))
      .on("error", (err) => {
        reject(new Error(`Final assembly failed: ${lastStderr || err.message}`));
      })
      .save(outputPath);
  });
}

/**
 * buildBackgroundBase
 * Scales each scene video to 1080x1920, applies blur + darken,
 * trims to exact duration, then concatenates.
 *
 * @param {Object[]} scenes   - scene objects with { duration_seconds, video_path }
 * @param {string}   workDir  - /tmp/ffmpeg-job-<uuid>
 * @returns {string}          - path to background_base.mp4
 */
function buildBackgroundBase(scenes, workDir) {
    const processedPaths = [];
    const vcodec = process.env.FFMPEG_VCODEC || 'libx264';
    console.log(`[assemble] Using video codec: ${vcodec}`);

    for (let i = 0; i < scenes.length; i++) {
        const scene = scenes[i];
        const inputPath = scene.video_path; // set by download.js
        const outputPath = path.join(workDir, `bg_scene_${i}.mp4`);

        // Check input file exists
        if (!fs.existsSync(inputPath)) {
            console.error(`[assemble] ❌ Input video NOT FOUND: ${inputPath}`);
            throw new Error(`Background input video not found: ${inputPath}`);
        }
        const inputStats = fs.statSync(inputPath);
        console.log(`[assemble] Input: ${inputPath} (${(inputStats.size / 1024 / 1024).toFixed(2)} MB)`);

        const vfFilters = [
            'scale=1080:1920:force_original_aspect_ratio=increase',
            'crop=1080:1920',
            'boxblur=8:8',
            'colorchannelmixer=rr=0.45:gg=0.45:bb=0.45',
        ].join(',');

        // Scale to fill 1080x1920, blur, darken
        // Use -stream_loop -1 before -i so if the video is shorter than duration_seconds, it loops
        const ffmpegCmd = [
            'ffmpeg -y',
            '-stream_loop -1',
            `-i "${inputPath}"`,
            `-t ${scene.duration_seconds}`,
            `-vf "${vfFilters}"`,
            `-c:v ${vcodec}`,
            '-preset fast',
            '-crf 23',
            '-an',
            `"${outputPath}"`,
        ].join(' ');

        console.log(`[assemble] Processing bg scene ${i + 1}/${scenes.length}...`);
        console.log(`[assemble] CMD: ${ffmpegCmd}`);
        execSync(ffmpegCmd, { stdio: 'inherit' });

        // Verify output was created
        if (!fs.existsSync(outputPath)) {
            console.error(`[assemble] ❌ bg_scene_${i}.mp4 was NOT created!`);
            throw new Error(`Background scene output not created: ${outputPath}`);
        }
        const outStats = fs.statSync(outputPath);
        console.log(`[assemble] ✅ bg_scene_${i}.mp4 created (${(outStats.size / 1024 / 1024).toFixed(2)} MB)`);
        processedPaths.push(outputPath);
    }

    // Write concat list file
    const concatListPath = path.join(workDir, 'bg_concat_list.txt');
    const concatContent = processedPaths.map(p => `file '${p}'`).join('\n');
    fs.writeFileSync(concatListPath, concatContent, 'utf8');
    console.log(`[assemble] Concat list written to ${concatListPath}`);
    console.log(`[assemble] Concat list contents:\n${concatContent}`);

    const backgroundBasePath = path.join(workDir, 'background_base.mp4');

    const concatCmd = [
        'ffmpeg -y',
        '-f concat',
        '-safe 0',
        `-i "${concatListPath}"`,
        '-c copy',
        `"${backgroundBasePath}"`,
    ].join(' ');

    console.log('[assemble] Concatenating background scenes...');
    console.log(`[assemble] CMD: ${concatCmd}`);
    execSync(concatCmd, { stdio: 'inherit' });

    // Verify background_base.mp4
    if (!fs.existsSync(backgroundBasePath)) {
        console.error('[assemble] ❌ background_base.mp4 was NOT created!');
        throw new Error(`background_base.mp4 not created: ${backgroundBasePath}`);
    }
    const bgStats = fs.statSync(backgroundBasePath);
    console.log(`[assemble] ✅ background_base.mp4 ready (${(bgStats.size / 1024 / 1024).toFixed(2)} MB)`);

    return backgroundBasePath;
}

/**
 * compositeFinalReel
 * Overlays the transparent ui_overlay.webm onto background_base.mp4,
 * merges audio.mp3, and trims to total_seconds.
 *
 * @param {string} backgroundBasePath - /tmp/.../background_base.mp4
 * @param {string} overlayWebmPath    - /tmp/.../ui_overlay.webm
 * @param {string} audioPath          - /tmp/.../audio.mp3
 * @param {number} totalSeconds       - exact final duration
 * @param {string} workDir            - /tmp/ffmpeg-job-<uuid>
 * @returns {string}                  - path to final_reel.mp4
 */
function compositeFinalReel(backgroundBasePath, overlayWebmPath, audioPath, totalSeconds, workDir) {
    const finalPath = path.join(workDir, 'final_reel.mp4');
    const vcodec = process.env.FFMPEG_VCODEC || 'libx264';

    // Log all input files and their sizes
    console.log('[assemble] ── Composite inputs ──');
    [backgroundBasePath, overlayWebmPath, audioPath].forEach((f, idx) => {
        const label = ['background', 'overlay', 'audio'][idx];
        if (fs.existsSync(f)) {
            const s = fs.statSync(f);
            console.log(`[assemble]   ${label}: ${f} (${(s.size / 1024 / 1024).toFixed(2)} MB)`);
        } else {
            console.error(`[assemble]   ❌ ${label} MISSING: ${f}`);
        }
    });

    // VP9 WebM with alpha channel is composited using overlay filter
    // [0:v] = blurred background
    // [1:v] = transparent UI overlay (VP9 alpha)
    // IMPORTANT: -c:v libvpx-vp9 BEFORE -i forces FFmpeg to use the libvpx decoder
    // which properly reads the alpha plane. Without it, FFmpeg's native VP9 decoder
    // strips alpha and decodes as opaque yuv420p (causing black background).
    const ffmpegCmd = [
        'ffmpeg -y',
        `-i "${backgroundBasePath}"`,            // input 0: background
        '-c:v libvpx-vp9',                       // force VP9 alpha decoder for next input
        `-i "${overlayWebmPath}"`,               // input 1: transparent UI overlay
        `-i "${audioPath}"`,                     // input 2: voiceover audio
        '-filter_complex',
        '"[1:v]format=yuva420p[overlay];[0:v][overlay]overlay=0:0[composited]"',
        '-map "[composited]"',
        '-map 2:a',
        `-t ${totalSeconds}`,
        `-c:v ${vcodec}`,
        '-preset fast',
        '-crf 20',
        '-c:a aac',
        '-b:a 192k',
        '-shortest',
        '-movflags +faststart',
        `"${finalPath}"`,
    ].join(' ');

    console.log('[assemble] Compositing final reel...');
    console.log(`[assemble] CMD: ${ffmpegCmd}`);
    execSync(ffmpegCmd, { stdio: 'inherit' });

    // Verify final output
    if (!fs.existsSync(finalPath)) {
        console.error('[assemble] ❌ final_reel.mp4 was NOT created!');
        throw new Error(`final_reel.mp4 not created: ${finalPath}`);
    }
    const finalStats = fs.statSync(finalPath);
    console.log(`[assemble] ✅ Final reel ready: ${finalPath} (${(finalStats.size / 1024 / 1024).toFixed(2)} MB)`);
    return finalPath;
}

module.exports = { buildAndRun, buildBackgroundBase, compositeFinalReel };
